model_name_or_path: /root/autodl-tmp/Qwen3-4B-Base/
stage: sft

dataset: maven_sft
dataset_dir: data/processed/
output_dir: /root/autodl-tmp/qwen-4b-mypretrain

do_train: true
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
num_train_epochs: 1
logging_steps: 10
bf16: true

# 训练时长控制
# max_steps: 20          # 只跑 x 个 optimizer step；优先级最高
save_steps: 200         # x 步自动保存
eval_steps: 100          # 每 x 步算一次 eval_loss

# 显存控制
gradient_checkpointing: false

# 权重加载
resume_from_checkpoint: null      # 或直接删除该键
overwrite_output_dir: true
save_safetensors: true            # 权衡安全

#wandb
report_to: wandb
run_name: maven_sft
wandb_project: maven-ecpo
wandb_tags: sft,qwen3-4b,maven
